### ISSUE TITLE
Washington, DC is not a state

### ISSUE THREAD

**Issue by eyeseast** [datadesk/latimes-statestyle#7]
I know it's really not :disappointed: but it's common enough for someone to write "Washington, DC" instead of "District of Columbia." And yet this fails:

```python
>>> statestyle.get('Washington, DC')
```

Special case, I know. And punctuation has to be accounted for. Still, worth handling, I think.

**Comment by palewire** [comment]
Yes. We need to add this.

**Comment by palewire** [comment]
Try:

```bash
$ pip install latimes-statestyle --upgrade
```

Then

```python
>>> import statestyle
>>> statestyle.get("Washington, DC")
```

**Comment by eyeseast** [comment]
That's a winner. Thank you.
