### ISSUE TITLE
Need an easier way to convert back to a dictionary

### ISSUE THREAD

**Issue by eyeseast** [datadesk/latimes-statestyle#8]
For serialization and such. Right now, I'm doing this awful thing:

```python
>>> ca = statestyle.get('ca')
>>> ca.__dict__
```

Would be nice to have one of these (or something similar):

```python
>>> ca = statestyle.get('ca')
>>> dict(ca)
>>> ca.to_dict()
```

Could actually make `statestyle.State` a `dict` subclass and just add `__getattr__` and `__setattr__` methods. Not sure if that's better.

**Comment by palewire** [comment]
We can do all of the above

**Comment by palewire** [comment]
Do this.
```bash
$ pip install latimes-statestyle --upgrade
```

Then this.
```python
>>> import statestyle
>>> o = statestyle.get("CA")
>>> o['name']
'California'
>>> dict(o)
{'name': 'California', 'ap': 'Calif.', 'fips': '6', 'postal': 'CA', 'type': 'state', 'stateface': 'E'}
```

**Comment by eyeseast** [comment]
You are my hero this week.

**Comment by palewire** [comment]
Happy to make improvements that are useful. What are you working on?

**Comment by eyeseast** [comment]
Couple things coming up. One going live today on vaccination laws
state-by-state. Using statestyle in combo with D3 (so needed JSON). But
I've used this on a bunch of projects at Frontline already. It is super
handy.

On Tue, Mar 24, 2015 at 1:25 PM, Ben Welsh <notifications@github.com> wrote:

> Happy to make improvements that are useful. What are you working on?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/datadesk/latimes-statestyle/issues/8#issuecomment-85608100>
> .
>



-- 
Chris Amico
Glass Eye Media LLC <http://glasseyemedia.org>

**Comment by palewire** [comment]
Am I crazy thing there might be a place for a D3 plugin or standalone JS library that does this same thing, assuming it doesn't exist already?

**Comment by eyeseast** [comment]
Standalone JS library would probably make sense, and shouldn't be hard.
It's essentially just a dictionary lookup. Maybe I'll do that.

On Tue, Mar 24, 2015 at 1:31 PM, Ben Welsh <notifications@github.com> wrote:

> Am I crazy thing there might be a place for a D3 plugin or standalone JS
> library that does this same thing, assuming it doesn't exist already?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/datadesk/latimes-statestyle/issues/8#issuecomment-85610099>
> .
>



-- 
Chris Amico
Glass Eye Media LLC <http://glasseyemedia.org>
